### ISSUE TITLE
Issue to fix for the avitool

### ISSUE THREAD

**Issue by itlinux** [avinetworks/avitools#23]
Hello all, 
we need to have the avitool update with the min version as follow:

ansible==4.2.0
ansible-core==2.11.2
avisdk==20.1.6
certifi==2021.5.30
cffi==1.14.6
chardet==4.0.0
cryptography==3.4.7
idna==2.10
Jinja2==3.0.1
jmespath==0.10.0
MarkupSafe==2.0.1
packaging==21.0
pycparser==2.20
pyparsing==2.4.7
PyYAML==5.4.1
requests==2.25.1
resolvelib==0.5.4
urllib3==1.26.6

**Comment by chaitanyaavi** [comment]
@itlinux Can you please provide some more details ?

**Comment by chaitanyaavi** [comment]
No response so closing this.
